### ISSUE TITLE
Generating specs without connecting to aws

### ISSUE THREAD

**Issue by madstap** [cognitect-labs/aws-api#136]
## Dependencies

``` clojure
{:deps {com.cognitect.aws/api       {:mvn/version "0.8.408"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.11.689"}
        com.cognitect.aws/s3        {:mvn/version "780.2.583.0"}}}
```

## Description with failing test case

I want to check that my request is valid in a unit-test, but to get the spec for a request it looks like I need a client that is connected to aws.

```clojure
(let [aws-profile "..."
      client (aws/client {:api                  :s3
                          :credentials-provider (aws.creds/profile-credentials-provider aws-profile)
                          :region-provider      (aws.region/profile-region-provider aws-profile)})]
  (s/valid? (aws/request-spec-key client :PutObject) (new-put-request ,,,)))

```

Would it be possible to get a hold of the spec without connecting to aws, or does the library dynamically build the spec using data from an api call?

**Comment by dchelimsky** [comment]
When you create a client there are no http requests going out, nor any dependency connectivity until you `aws/invoke` an op. Can you execute that code with your internet connection disabled?

**Comment by dchelimsky** [comment]
> does the library dynamically build the spec using data from an api call?

No. The specs ship in the service libraries (generated by a build process). When you include `com.cognitect.aws/s3`. They are not loaded into the spec registry until you invoke a function that needs specs, like `request-spec-key` or `validate-requests`. Once loaded, you can see them in the spec registry e.g. `(keys (s/registry))`.

We haven't documented their names or location because that's an implementation detail that could change, so what you're doing, `(aws/request-spec-key client :PutObject)`, is the correct approach.

**Comment by dchelimsky** [comment]
I'm closing this for now, because I don't think there is an issue here. Feel free to reopen it if it turns out that there _is_ an issue that I'm not seeing.
