### ISSUE TITLE
aws-api should use official `AWS_SHARED_CREDENTIALS_FILE` for providing the coordinates to the `credentials` file

### ISSUE THREAD

**Issue by FieryCod** [cognitect-labs/aws-api#188]
Patch for this issue is here: https://github.com/cognitect-labs/aws-api/pull/187

**Comment by dchelimsky** [comment]
Thanks for the patch, but we don't accept PRs.

That said, the [docs you referenced](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) make no mention of the `AWS_CREDENTIAL_PROFILES_FILE` we're using, so we may end up deprecating support for that var as we add support for `AWS_SHARED_CREDENTIALS_FILE` in order to align w/ the AWS CLI.

**Comment by dchelimsky** [comment]
Actually, the [java sdk v1](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) uses `AWS_SHARED_CREDENTIALS_FILE`, so we'll keep it.

**Comment by dchelimsky** [comment]
https://github.com/cognitect-labs/aws-api/commit/c9c441067bd301eced32a9afacbce1aeab1e65e8

I'll leave this open until it's released.

**Comment by dchelimsky** [comment]
Released today with aws-api-0.5.561
