### ISSUE TITLE
Support for CloudWatch (and CloudWatchEvents)?

### ISSUE THREAD

**Issue by grzm** [cognitect-labs/aws-api#32]
I think I must be missing it, but I don’t see Cloudwatch among the releases for the cognitect aws client api. https://github.com/cognitect-labs/aws-api/blob/master/latest-releases.edn

I'm looking for something that would correspond to the following:
- https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/index.html
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatch/AmazonCloudWatchClient.html

**Comment by dchelimsky** [comment]
What you're looking for is "monitoring". We're going by the "uid" value in the metadata for each service, e.g. https://github.com/aws/aws-sdk-js/blob/master/apis/monitoring-2010-08-01.normal.json#L11. 

Most of the time the uids (from which we name our releases) align with the service names, but this is one of the exceptions. I'm going to leave this open because we need to have a better way to communicate about this.

**Comment by grzm** [comment]
Thanks, @dchelimsky !

**Comment by dchelimsky** [comment]
@grzm I changed the format of https://github.com/cognitect-labs/aws-api/blob/master/latest-releases.edn to include the service full names. Does that resolve this issue for you?

**Comment by dchelimsky** [comment]
Closing this as I believe we've resolved the issue.
