### ISSUE TITLE
apigateway unable to create new api with region parameter

### ISSUE THREAD

**Issue by rnandan273** [cognitect-labs/aws-api#89]
Unable to create a new Rest API with the region parameter.
It always defaults to us-west-1 even if the client is initialised with region parameter and the createRestApi is also specified with region parameter

(aws/invoke 
  (aws/client {:api :apigateway
                      :credentials-provider (credentials/basic-credentials-provider
                                             {:region "us-east-2"
                                              :access-key-id     "xxx"
                                              :secret-access-key "xxxx"})})
   {:op :CreateRestApi :request {:name "test-rest-api" :region "us-east-2"}})

This creates a REST API in "us-west-1" and not "us-east-2"

aws cli and nodejs SDK behave as expected, but cognitect aws api has this issue

**Comment by dchelimsky** [comment]
The docs for `:CreateRestApi` do not indicate that `:region` is part of the request:

```
(def apigw (aws/client {:api :apigateway}))
(-> apigw
    aws/ops
    :CreateRestApi)
{:name "CreateRestApi",
 :documentation "<p>Creates a new <a>RestApi</a> resource.</p>",
 :request
 {:endpointConfiguration {:types [:seq-of string]},
  :description string,
  :tags [:map-of string string],
  :name string,
  :apiKeySource string,
  :policy string,
  :cloneFrom string,
  :binaryMediaTypes [:seq-of string],
  :version string,
  :minimumCompressionSize integer},
 :required [:name],
 :response
 {:endpointConfiguration {:types [:seq-of string]},
  :description string,
  :tags [:map-of string string],
  :name string,
  :warnings [:seq-of string],
  :apiKeySource string,
  :policy string,
  :binaryMediaTypes [:seq-of string],
  :id string,
  :createdDate timestamp,
  :version string,
  :minimumCompressionSize integer}}
```

That's because it uses the region your configured on your client. To make a client in a specific region, you pass in the `:region` directly to the client fn, not as part of the `:credentials`:

```
(def apigw (aws/client {:api :apigateway
                        :region "us-east-2"}))
```

Do that and then

```
  (aws/invoke apigw {:op :CreateRestApi
                     :request {:name "test-rest-api"}})
```

.. and it will work as expected.

Relevant docs:
* `:CreateRestApi` per above
* https://cognitect-labs.github.io/aws-api/cognitect.aws.client.api-api.html#cognitect.aws.client.api/client
* https://cognitect-labs.github.io/aws-api/cognitect.aws.credentials-api.html#cognitect.aws.credentials/basic-credentials-provider
